[package]
name = "essaim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "=0.7.0"
bevy = "0.10.0"
rand = "0.8.5"



